-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 12:07:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DIRECTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIRECTIONS` (
  `id_direction` INT NOT NULL AUTO_INCREMENT,
  `sigle` VARCHAR(15) NULL,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_direction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FONCTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FONCTIONS` (
  `id_fonction` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_fonction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AGENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AGENTS` (
  `id_agent` INT NOT NULL AUTO_INCREMENT,
  `matricule` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `fonction*` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `direction` VARCHAR(45) NULL,
  `email` VARCHAR(50) NULL,
  `AGENTScol` VARCHAR(45) NULL,
  `DIRECTION_id_direction` INT NOT NULL,
  `FONCTIONS_id_fonction` INT NOT NULL,
  PRIMARY KEY (`id_agent`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `matricule_UNIQUE` (`matricule` ASC),
  INDEX `fk_AGENTS_DIRECTION1_idx` (`DIRECTION_id_direction` ASC),
  INDEX `fk_AGENTS_FONCTIONS1_idx` (`FONCTIONS_id_fonction` ASC),
  CONSTRAINT `fk_AGENTS_DIRECTION1`
    FOREIGN KEY (`DIRECTION_id_direction`)
    REFERENCES `mydb`.`DIRECTIONS` (`id_direction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENTS_FONCTIONS1`
    FOREIGN KEY (`FONCTIONS_id_fonction`)
    REFERENCES `mydb`.`FONCTIONS` (`id_fonction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ETAT_DOSSIERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ETAT_DOSSIERS` (
  `id_etat_dossier` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_etat_dossier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOSSIERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DOSSIERS` (
  `id_dossier` INT NOT NULL AUTO_INCREMENT,
  `num_dossier` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `resume` TEXT NULL,
  `commentaire` TEXT NULL,
  `etat` VARCHAR(45) NULL,
  `ETAT_DOSSIERS_id_etat_dossier` INT NOT NULL,
  PRIMARY KEY (`id_dossier`),
  INDEX `fk_DOSSIERS_ETAT_DOSSIERS1_idx` (`ETAT_DOSSIERS_id_etat_dossier` ASC),
  CONSTRAINT `fk_DOSSIERS_ETAT_DOSSIERS1`
    FOREIGN KEY (`ETAT_DOSSIERS_id_etat_dossier`)
    REFERENCES `mydb`.`ETAT_DOSSIERS` (`id_etat_dossier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ETAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ETAT` (
  `id_etat` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_etat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TACHES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TACHES` (
  `id_tache` INT NOT NULL AUTO_INCREMENT,
  `libelle_tache` VARCHAR(45) NULL,
  `budget` VARCHAR(45) NULL,
  `delai` DATE NULL,
  `AGENTS_id_agent` INT NOT NULL,
  `DOSSIERS_id_dossier` INT NOT NULL,
  `ETAT_id_etat` INT NOT NULL,
  PRIMARY KEY (`id_tache`),
  INDEX `fk_TACHES_AGENTS1_idx` (`AGENTS_id_agent` ASC),
  INDEX `fk_TACHES_DOSSIERS1_idx` (`DOSSIERS_id_dossier` ASC) ,
  INDEX `fk_TACHES_ETAT1_idx` (`ETAT_id_etat` ASC),
  CONSTRAINT `fk_TACHES_AGENTS1`
    FOREIGN KEY (`AGENTS_id_agent`)
    REFERENCES `mydb`.`AGENTS` (`id_agent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TACHES_DOSSIERS1`
    FOREIGN KEY (`DOSSIERS_id_dossier`)
    REFERENCES `mydb`.`DOSSIERS` (`id_dossier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TACHES_ETAT1`
    FOREIGN KEY (`ETAT_id_etat`)
    REFERENCES `mydb`.`ETAT` (`id_etat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
